accounts:
- description: 价值投资深度分析
  enabled: true
  id: '5739488179'
  name: Elon翻开每一页
  url: https://xueqiu.com/u/5739488179
- description: 中海油分析专家
  enabled: true
  id: '6308001210'
  name: czy710
  url: https://xueqiu.com/u/6308001210
- description: ''
  enabled: true
  id: '6249637706'
  name: 海豚研究君
  url: https://xueqiu.com/u/6249637706
- description: ''
  enabled: true
  id: '9951187724'
  name: MZInvest
  url: https://xueqiu.com/u/9951187724
- description: ''
  enabled: true
  id: '1156957441'
  name: 林氪长坡厚雪
  url: https://xueqiu.com/u/1156957441
- description: ''
  enabled: true
  id: '4641860462'
  name: Waterzzz
  url: https://xueqiu.com/u/4641860462
- description: ''
  enabled: true
  id: '1936609590'
  name: 逸修1
  url: https://xueqiu.com/u/1936609590
- description: ''
  enabled: true
  id: '8790885129'
  name: 超级鹿鼎公
  url: https://xueqiu.com/u/8790885129
- description: ''
  enabled: true
  id: '3181890538'
  name: 林文丰
  url: https://xueqiu.com/u/3181890538
- description: 价值投资分析
  enabled: true
  id: '6865675576'
  name: 永庆好公司
  url: https://xueqiu.com/u/6865675576
- description: 港股专业分析
  enabled: true
  id: '3075122481'
  name: 港股解码
  url: https://xueqiu.com/u/3075122481
